### ISSUE TITLE
Fix Multiple Choice Answers

### ISSUE THREAD

**Issue by koaning** [instruqt/instruqt#46] opened 2019-08-20 07:22 UTC
**Describe the bug**

I am using the user interface to create answers. These are the answers: 

- `df.sort_values(by=["gender", "age"], ascending=[False, False])`
- `df.sort_values(by=["gender", "age"], ascending=[False, True])`
- `df.sort_values(by=["gender", "age"], ascending=[True, False])`
- `df.sort_values(by=["gender", "age"], ascending=[True, False])`

But once I save these, this comes out; 

![image](https://user-images.githubusercontent.com/1019791/63326227-13d1ba80-c32c-11e9-826d-fbd87d2fc994.png)

**Expected Behavior** 
I should just see the four questions.

**Comment by amochtar** [comment] 2019-08-20 15:49
This was caused by a faulty deserialization from the database... But that has been fixed now :smile:

**Closed by amochtar** 2019-08-20 15:49 UTC
Labels: bug
